---
# Tika installation for ddhn.tools

- name: "TIKA | Running Tool Setup."
  include_tasks: tool.yml
  vars:
    item: "{{ ddhn.tools.tika }}"

- name: "TIKA | Download the application jar."
  get_url:
    url: "{{ ddhn.tools.tika.installer.loc }}"
    dest: "{{ ddhn.tools.tika.dests.lib }}/tika-app-{{ tika_version }}.jar"

- name: "TIKA | Copy the tika shell file."
  template:
    src: "usr/local/lib/tika/tika.sh"
    dest: "{{ ddhn.tools.tika.dests.lib }}/tika.sh"
    mode: a+x

- name: "TIKA | Create symlink for shell file."
  file:
    src: "{{ ddhn.tools.tika.dests.lib }}/tika.sh"
    dest: "{{ ddhn.tools.tika.dests.bin }}/tika-gui"
    state: link
