---
# ddhn.setup default values
ddhn_env_apt_defaults:
  # Source control a
  - "git"
  # Debian Stretch lacks the ability to download apt over HTTPS
  - "apt-transport-https"
  # Install some helper network tools
  - "psmisc"
  - "net-tools"
  # Zip and unzip are always handy
  - zip
  - unzip
  # Open JDK 8 for Java
  - openjdk-11-jre
  - openjdk-11-doc
  - openjdk-11-source
  # GNOME desktop and Nemo add on for icon display
  - task-gnome-desktop
  - nemo

virtualbox_remove_os_packages: true
virtualbox_x11: true
local_virtualbox_iso: "/usr/share/virtualbox/VBoxGuestAdditions.iso"

ddhn:
  setup:
    prereqs:
      apt: "{{ ddhn_env_prereqs_apt | default (ddhn_env_apt_defaults) }}"
    hostname: "{{ ddhn_env_hostname | default('localhost') }}"
    hostdomain: "{{ ddhn_env_hostdomain | default('localdomain') }}"
    fqdn: "{{ ddhn_env_fqdn | default('localhost.localdomain') }}"
    timezone: "{{ ddhn_env_timezone | default('Europe/London') }}"
    iptables:
      interfaces: "{{ ddhn_env_http_interfaces | default([]) }}"
    ip:
      v4: "{{ ddhn_env_ip | default('127.0.0.1') }}"
      v6: "{{ ddhn_env_ip_v6 | default('') }}"
    port:
      http: "{{ ddhn_env_port_http | default('') }}"
      https: "{{ ddhn_env_port_https | default('') }}"
    open_ports: "{{ ddhn_env_open_ports | default([]) }}"
    limited_account:
      name: "{{ ddhn_env_user_name | default('vagrant') }}"
      password: "{{ ddhn_env_user_password | default('$6$D.o3KgyK$3k1LYzMBfQBTXfp0GMzAuKpLp1TwKGb/Q0eVc5sP7sdlb.0TIeBOMISmIidT8CFqdOwU240Bnfp8On7484UCk1') }}"
      home: "{{ ddhn_env_user_home | default('/home/vagrant') }}"
    default_locale: en_GB.UTF-8
    locales:
      - da_DK.UTF-8
      - de_AT.UTF-8
      - de_BE.UTF-8
      - de_CH.UTF-8
      - de_DE.UTF-8
      - en_CA.UTF-8
      - en_GB.UTF-8
      - en_US.UTF-8
      - es_ES.UTF-8
      - et_EE.UTF-8
      - fi_FI.UTF-8
      - fr_BE.UTF-8
      - fr_FR.UTF-8
      - hr_HR.UTF-8
      - hu_HU.UTF-8
      - is_IS.UTF-8
      - it_IT.UTF-8
      - lt_LT.UTF-8
      - lv_LV.UTF-8
      - nl_BE.UTF-8
      - nl_NL.UTF-8
      - nn_NO.UTF-8
      - pt_PT.UTF-8
      - ro_RO.UTF-8
      - sv_SE.UTF-8
      - tr_TR.UTF-8
      - uk_UA.UTF-8

